version: "3.9"

services:
  flask_app:
    container_name: MC-Flask-App
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    command:  ["gunicorn", "-w", "4", "-b", "0.0.0.0:4000", "app:app"]